name: Publish Package to npmjs
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: disclaimer-api
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm publish
